- name: variabless from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
  - name: DURATION
    prompt: please enter the duration of the course
  - name: TRAINER
    prompt: please enter the trainer name
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"