- name: gathering facts
  hosts: web
  become: yes
  tasks:
  - name: print the facts
    ansible.builtin.debug:
      msg: " {{ ansible_facts }} " #here, ansible_facts variable is automatically set by it