- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # shell module login to the server and execute command inside
    # command module, just issues the command

  - name : check the process
    ansible.builtin.shell: ps -ef | grep ssh # this works as we are using shell for pipes
    register: output

  - name : check the process
    ansible.builtin.command: ps -ef | grep ssh # this won't works as we are using command for pipes
    register: output
