- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-00a727baf5d630249" # replace your subnet id
    sg_id: "sg-0e6caef1c55b2f3b1"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc-subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances